# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: poolDaniel

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true
  displayName: 'install Node js'
- task: CmdLine@2
  inputs:
    script: |
      npm install
      npm rebuild
      npm build
  displayName: 'install and build'
- task: CmdLine@2
  inputs:
    script: 'npm run test:coverage'
  condition: succeeded()
  displayName: 'Test Coverage'